In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers


array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.view()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
id(numbers)

1843333569520

In [7]:
id(numbers2)

1843338393904

In [8]:
numbers[1] *= 20


In [9]:
numbers


array([ 1, 40,  3,  4,  5])

In [10]:
numbers2

array([ 1, 40,  3,  4,  5])